export const ProductEquipamentoCABSchema = {
  name: "ProductEquipamento",
  primaryKey: "idCentro",
  properties: {
    idCentro: "string",
    idDeposito: "string",
    area: "string",
    nivel: "string",
    sistema: "string",
    tipoContagem: "string",
    tipoStatusAtendimento: "string",
    tipoStatusContagem: "string",
    contagemCega: "string",
    contagemFechada: "string",
    Contador: "string",
    Contado: "bool",
    Tipo: "string",
    registro: "string",
    idOrdemContagem: "string",
    descricao: "string",
    foraDaCurva: "string",
    msg: "string",
    tema: "string",
    lstProduto: "ProductEquipamento[]",
  },
};
